version: "3.9"

services:
  mongo-auth:
    image: cmerbruno/custom-mongo:v01
    container_name: mongo-auth
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongoadmin
    ports:
      # Em k8s: Service ClusterIP 2031 -> 27017. Localmente expomos igual.
      - "2031:27017"
    volumes:
      - mongo_data_auth:/data/db

  scheduler-auth:
    build: .
    container_name: scheduler-auth
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3021:3021"
    volumes:
      - uploads_storage:/uploads

volumes:
  mongo_data_auth:
  uploads_storage: